import type { Env } from './types';
import { Lobby } from './Lobby';
import { GameRoom } from './GameRoom';
// Generated by `vite build` with adapter-cloudflare.
// @ts-expect-error: file is build output and not present pre-build
import kitWorker from '../.svelte-kit/cloudflare/_worker.js';

export { Lobby, GameRoom };

export default {
  async fetch(request: Request, env: Env, _ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url);

    if (url.pathname.startsWith('/api/lobby/')) {
      const lobby = env.LOBBY.get(env.LOBBY.idFromName('default'));
      if (url.pathname === '/api/lobby/create' && request.method === 'POST') {
        const body = (await request.json()) as { roundCount?: number };
        const roundCount = Number(body?.roundCount) || 3;
        const { roomId } = await lobby.createRoom(roundCount);
        return Response.json({ roomId });
      }
      if (url.pathname === '/api/lobby/rooms' && request.method === 'GET') {
        const { rooms } = await lobby.listRooms();
        return Response.json({ rooms });
      }
      if (url.pathname === '/api/lobby/join' && request.method === 'POST') {
        const body = (await request.json()) as { roomId?: string; playerName?: string };
        const roomId = body?.roomId;
        if (!roomId) return Response.json({ error: 'roomId required' }, { status: 400 });
        const result = await lobby.joinRoom(roomId, body.playerName);
        if ('error' in result) return Response.json(result, { status: 400 });
        const origin = url.origin;
        return Response.json({ ...result, wsUrl: `${origin}/room/${roomId}` });
      }
      return new Response('Not Found', { status: 404 });
    }

    const roomMatch = /^\/room\/([^/]+)$/.exec(url.pathname);
    if (roomMatch) {
      const upgrade = request.headers.get('Upgrade');
      if (upgrade?.toLowerCase() === 'websocket') {
        const roomId = roomMatch[1];
        const room = env.GAME_ROOM.get(env.GAME_ROOM.idFromName(roomId));
        return room.fetch(request);
      }
      return new Response('Expected WebSocket', { status: 426 });
    }

    return kitWorker.fetch(request, env, _ctx);
  },
} satisfies ExportedHandler<Env>;
